# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79a8004cf4ebfbd4d474aa5f67a574cc33d2f4dd8683d930e691c10e12e653e178ca9df34b96a63fa2e8700163e99e1753007b9ea80c245d949cc2e182f85f0d

test:
  secret_key_base: ecd2d181f87d818f1ada6f31869cfe6fce7c32751e48ca8288a505a87f24bdc28d469cb517c8aab26d30e8497393600007126fe3d44e2e665f39f7ddb0f40a1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
